imgsys: fix modpost symbol undefined error and missing MODULE_LICENSE
Fix modpost undefined error and missing MODULE_LICENSE with
the compile log:
ERROR: modpost: missing MODULE_LICENSE()
ERROR: modpost: "imgsys_main_init" undefined
ERROR: modpost: "imgsys_main_uninit"  undefined
ERROR: modpost: "imgsys_traw_set_initial_value"  undefined
ERROR: modpost: "imgsys_main_set_init" undefined
ERROR: modpost: "imgsys_traw_set_initial_value_hw" undefined
ERROR: modpost: "imgsys_traw_uninit" undefined
ERROR: modpost: "imgsys_traw_debug_dump" undefined
ERROR: modpost: "allocate_working_buffer_helper" is a static EXPORT_SYMBOL
ERROR: modpost: "release_working_buffer_helper" is a static EXPORT_SYMBOL
ERROR: modpost: "ipesys_me_debug_dump_local"    is a static EXPORT_SYMBOL

Change-Id: Iec8540f9c02352f5439ba623941cd81b0c1995fa
Signed-off-by: Efang Chung <efang.chung@mediatek.com>